version: '3.8'

services:
  api:
    image: gcr.io/tcc-lucas-pierre/api
    build: ./src/api
    container_name: api
    volumes:
      - ./src/mnt:/mnt
    env_file:
      - 'variables.env'
    ports:
      - 5000:5000
    networks:
      - network

  client:
    image: gcr.io/tcc-lucas-pierre/client
    build: ./src/client
    container_name: client
    volumes:
      - ./src/client:/home/jovyan/notebooks
      - ./src/mnt:/mnt
    ports:
      - 8888:8888
    env_file:
      - 'variables.env'
    links:
      - api:api
    depends_on:
      - api
    networks:
      - network

  mlflow:
    container_name: mlflow
    build: ./src/mlflow
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: ${ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${SECRET_KEY}
    ports:
      - "12000:5000"

networks:
    network: {}