version: '3.8'

services:
  api:
    image: gcr.io/tcc-lucas-pierre/api
    build: ./src/api
    container_name: api
    volumes:
      - ./src/mnt:/mnt
    env_file:
      - 'variables.env'
    ports:
      - 5000:5000
    networks:
      - network

  client:
    image: gcr.io/tcc-lucas-pierre/client
    build: ./src/client
    container_name: client
    volumes:
      - ./src/client:/home/jovyan/notebooks
      - ./src/mnt:/mnt
    ports:
      - 8888:8888
    env_file:
      - 'variables.env'
    networks:
      - network

  mlflow:
    image: gcr.io/tcc-lucas-pierre/mlflow
    container_name: mlflow
    build: ./src/mlflow
    volumes:
      - ./src/mnt:/mnt
    env_file:
      - 'variables.env'
    ports:
      - "12000:5000"
    networks:
      - network

networks:
    network: {}