apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: "{{ .Values.service.name }}"
  name: "{{ .Values.service.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: "{{ .Values.service.name }}"
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/network: "true"
        io.kompose.service: "{{ .Values.service.name }}"
    spec:
      containers:
        - env:
            - name: API_HOST
              value: "{{ .Values.service.name }}"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/mnt/credentials.json"
            - name: QUEUE_IMAGERY
              value: "{{ .Values.queue.imagery }}"
            - name: QUEUE_INFERENCE
              value: "{{ .Values.queue.inference }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: api
          volumeMounts:
            - name: credentials
              mountPath: /mnt
          ports:
            - containerPort: 5000
          resources: {}
      volumes:
        - name: credentials
          secret:
            secretName: credentials
      restartPolicy: Always
status: {}
