apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}-lb"
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: "{{ .Values.service.name }}"
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000