apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mlflow
  name: mlflow
spec:
  ports:
    - name: "5000"
      port: 5000 # client
      targetPort: 5000 # exposes
  selector:
    io.kompose.service: mlflow
status:
  loadBalancer: {}
