image:
  repository: gcr.io/tcc-lucas-pierre/api
  pullPolicy: IfNotPresent
  tag: ""

service:
  name: api

mlflow:
  password: mlflow
  user: mlflow
  artifact_url: gs://tcc-mlflow
  database_url: postgresql://mlflow:mlflow@0.0.0.0:3306/mlflow-db

queue:
  imagery: imagery
  inference: inference
