apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mlflow
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mlflow
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/network: "true"
        io.kompose.service: mlflow
    spec:
      containers:
        - env:
            - name: MLFLOW_PASSWORD
              value: "{{ .Values.mlflow.password }}"
            - name: MLFLOW_USER
              value: "{{ .Values.mlflow.user }}"
            - name: MLFLOW_ARTIFACT_URL
              value: "{{ .Values.mlflow.artifact_url }}"
            - name: MLFLOW_DATABASE_URL
              value: "{{ .Values.mlflow.database_url }}"
          image: gcr.io/tcc-lucas-pierre/mlflow
          name: mlflow
          resources: {}
      restartPolicy: Always
status: {}
