name: CD4ML
run-name: ${{ github.run_id }} - ${{ github.ref_name }}
on:
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - 'main'
jobs:
  BuildAPI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/api/requirements.txt
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Unit Tests
        run: python -m pytest src/api/tests/
      - name: Lint with flake8
        run: |
           pip install flake8
           flake8 --max-line-length=100 ./src/api/main.py
        continue-on-error: true
      - name: Build Docker Image
        run: |
          gcloud auth configure-docker -q
          docker build ./src/api -t gcr.io/tcc-lucas-pierre/api:${{ github.ref_name }}
      - name: Publish Docker Image
        run: |
          docker push gcr.io/tcc-lucas-pierre/api:${{ github.ref_name }}
      - name: 'Job Status!'
        run: echo "${{ job.status }}!"
  BuildImagery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/tasks/imagery/requirements.txt
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Lint with flake8
        run: |
           pip install flake8
           flake8 --max-line-length=100 ./src/tasks/imagery/main.py
        continue-on-error: true
      - name: Build Docker Image
        run: |
          gcloud auth configure-docker -q
          docker build ./src/tasks/imagery -t gcr.io/tcc-lucas-pierre/imagery:${{ github.ref_name }}
      - name: Publish Docker Image
        run: |
          docker push gcr.io/tcc-lucas-pierre/imagery:${{ github.ref_name }}
      - name: 'Job Status!'
        run: echo "${{ job.status }}!"
  BuildInference:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/tasks/inference/requirements.txt
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Lint with flake8
        run: |
           pip install flake8
           flake8 --max-line-length=100 ./src/tasks/inference/main.py
        continue-on-error: true
      - name: Build Docker Image
        run: |
          gcloud auth configure-docker -q
          docker build ./src/tasks/inference -t gcr.io/tcc-lucas-pierre/inference:${{ github.ref_name }}
      - name: Publish Docker Image
        run: |
          docker push gcr.io/tcc-lucas-pierre/inference:${{ github.ref_name }}
      - name: 'Job Status!'
        run: echo "${{ job.status }}!"
  DeployAPIDev:
    runs-on: ubuntu-latest
    needs: [BuildAPI, BuildImagery, BuildInference]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Deploy API Dev
        run: |
          gcloud auth configure-docker -q
          gcloud container clusters get-credentials tcc-cluster --region us-east1
          helm upgrade --install --set image.tag=${{ github.ref_name }},service.name=api-${{ github.ref_name }},queue.imagery=imagery-${{ github.ref_name }},queue.inference=inference-${{ github.ref_name }}  api-${{ github.ref_name }} ./api-chart
          helm list
      - name: 'Job Status!'
        run: echo "${{ job.status }}!"
  DeployImageryDev:
    runs-on: ubuntu-latest
    needs: [BuildAPI, BuildImagery, BuildInference]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'deploy'
        name: 'Deploy Imagery in dev'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          working_directory: './src/tasks/imagery'
          version: '${{ github.ref_name }}'

      - name: Create Imagery Queue in Dev
        run: |
          gcloud auth configure-docker -q
          gcloud tasks queues create imagery-${{ github.ref_name }} --location southamerica-east1 --routing-override=service:imagery
          gcloud tasks queues describe imagery-${{ github.ref_name }}

      - name: 'Job Status!'
        run: echo "${{ job.status }}!"
  DeployInferenceDev:
    runs-on: ubuntu-latest
    needs: [BuildAPI, BuildImagery, BuildInference]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'deploy'
        name: 'Deploy Inference in Dev'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          working_directory: './src/tasks/inference'
          version: '${{ github.ref_name }}'

      - name: Create Inference Queue in Dev
        run: |
          gcloud auth configure-docker -q
          gcloud tasks queues create inference-${{ github.ref_name }} --location southamerica-east1 --routing-override=service:inference
          gcloud tasks queues describe inference-${{ github.ref_name }}

      - name: 'Job Status!'
        run: echo "${{ job.status }}!"

      - name: 'Job Status!'
        run: echo "${{ job.status }}!"
