name: CD4ML
run-name: ${{ github.ref }}
on: [pr]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "${{ job.status }}."