name: CD4ML - Integration
run-name: ${{ github.run_id }} - ${{ github.head_ref }}
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'main'
env:
  API_HOST: 34.73.236.32
  MLFLOW_HOST: 35.231.130.51
  PROJECT_ID: tcc-lucas-pierre
  BUCKET_NAME: tcc-clothes
  AUC_THRESHOLD: 0.7

jobs:
  BuildAPI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/api/requirements.txt
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Unit Tests
        run: python -m pytest src/api/tests/
      - name: Lint with flake8
        run: |
           pip install flake8
           flake8 --max-line-length=100 ./src/api/main.py
        continue-on-error: true
      - name: Build Docker Image
        run: |
          gcloud auth configure-docker -q
          docker build ./src/api -t gcr.io/tcc-lucas-pierre/api:${{ github.head_ref }}
      - name: Publish Docker Image
        run: |
          docker push gcr.io/tcc-lucas-pierre/api:${{ github.head_ref }}
      - name: 'Job Status!'
        run: echo "${{ job.status }}!"
  BuildImagery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/tasks/imagery/requirements.txt
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Lint with flake8
        run: |
           pip install flake8
           flake8 --max-line-length=100 ./src/tasks/imagery/main.py
        continue-on-error: true
      - name: Build Docker Image
        run: |
          gcloud auth configure-docker -q
          docker build ./src/tasks/imagery -t gcr.io/tcc-lucas-pierre/imagery:${{ github.head_ref }}
      - name: Publish Docker Image
        run: |
          docker push gcr.io/tcc-lucas-pierre/imagery:${{ github.head_ref }}
      - name: 'Job Status!'
        run: echo "${{ job.status }}!"
  BuildInference:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/tasks/inference/requirements.txt
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Lint with flake8
        run: |
           pip install flake8
           flake8 --max-line-length=100 ./src/tasks/inference/main.py
        continue-on-error: true
      - name: Build Docker Image
        run: |
          gcloud auth configure-docker -q
          docker build ./src/tasks/inference -t gcr.io/tcc-lucas-pierre/inference:${{ github.head_ref }}
      - name: Publish Docker Image
        run: |
          docker push gcr.io/tcc-lucas-pierre/inference:${{ github.head_ref }}
      - name: 'Job Status!'
        run: echo "${{ job.status }}!"
  DeployAPIDev:
    runs-on: ubuntu-latest
    needs: [BuildAPI, BuildImagery, BuildInference]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Deploy API Dev
        run: |
          gcloud auth configure-docker -q
          gcloud container clusters get-credentials tcc-cluster --region us-east1
          helm upgrade --install --set image.tag=${{ github.head_ref }},service.name=api-${{ github.head_ref }},queue.imagery=imagery-${{ github.head_ref }},queue.inference=inference-${{ github.head_ref }}  api-${{ github.head_ref }} ./charts/api
          helm list
      - name: 'Job Status!'
        run: echo "${{ job.status }}!"
  DeployImageryDev:
    runs-on: ubuntu-latest
    needs: [BuildAPI, BuildImagery, BuildInference]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'deploy'
        name: 'Deploy Imagery in dev'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          working_directory: './src/tasks/imagery'
          version: '${{ github.head_ref }}'

      - name: Create Imagery Queue in Dev
        run: |
          gcloud auth configure-docker -q
          gcloud tasks queues create imagery-${{ github.head_ref }} --location southamerica-east1 --routing-override=service:imagery-${{ github.head_ref }}
          gcloud tasks queues describe imagery-${{ github.head_ref }}
        continue-on-error: true

      - name: 'Job Status!'
        run: echo "${{ job.status }}!"
  DeployInferenceDev:
    runs-on: ubuntu-latest
    needs: [BuildAPI, BuildImagery, BuildInference]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'deploy'
        name: 'Deploy Inference in Dev'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          working_directory: './src/tasks/inference'
          version: '${{ github.head_ref }}'

      - name: Create Inference Queue in Dev
        run: |
          gcloud auth configure-docker -q
          gcloud tasks queues create inference-${{ github.head_ref }} --location southamerica-east1 --routing-override=service:inference-${{ github.head_ref }}
          gcloud tasks queues describe inference-${{ github.head_ref }}
        continue-on-error: true

      - name: 'Job Status!'
        run: echo "${{ job.status }}!"
  MLPipeline:
    runs-on: ubuntu-latest
    needs: [DeployAPIDev, DeployImageryDev, DeployInferenceDev]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Run experiments for models
        run: |
          pip install --upgrade pip
          pip install -r src/ml_pipeline/requirements.txt
          python src/ml_pipeline/main.py ${{ github.head_ref }} ${AUC_THRESHOLD}

      - name: 'Job Status!'
        run: echo "${{ job.status }}!"
