name: CD4ML
run-name: ${{ github.run_id }} - ${{ github.ref_name }}
on:
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - 'main'
jobs:
  BuildAPI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/api/requirements.txt
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Unit Tests
        run: python -m pytest src/api/tests/
      - name: Lint with flake8
        run: |
           pip install flake8
           flake8 .
        continue-on-error: true
      - name: 'Job Status!'
        run: echo "${{ job.status }}!"